import asyncio
import xml.etree.ElementTree as ET
import tempfile
import os
import sys
from logix_designer_sdk import LogixProject, StdOutEventLogger

async def open_project(acd_path: str):
    """Open the .ACD project file (silently)"""
    print(f"\nOpening project: {acd_path}")
    # None suppresses all SDK logging output
    project = await LogixProject.open_logix_project(acd_path, None)
    print("Project opened successfully")
    return project


def create_temp_l5x_file():
    """Create an empty temporary file (path generated by Windows)"""
    print("\nCreating temporary L5X file")
    tmp = tempfile.NamedTemporaryFile(suffix=".L5X", delete=False)
    tmp.close()
    print(f"Temporary file path: {tmp.name}")
    return tmp.name
    
def create_temp_acd_file():
    """Create an empty temporary file (path generated by Windows)"""
    print("\nCreating temporary ACD file")
    tmp = tempfile.NamedTemporaryFile(suffix=".ACD", delete=False)
    tmp.close()
    print(f"Temporary file path: {tmp.name}")
    return tmp.name


async def save_as_l5x(project, l5x_path: str):
    """Export the opened project to the temporary L5X file"""
    print(f"\nExporting project to L5X file")
    await project.save_as(l5x_path, True, detailed_l5x=True)
    print("L5X export finished")


def parse_controller_name(l5x_path: str) -> str:
    """Parse the exported L5X file and extract the controller name"""
    print(f"\nParsing L5X file for controller name")
    tree = ET.parse(l5x_path)
    root = tree.getroot()

    # Explicit None check to avoid DeprecationWarning and future issues
    controller = root.find("Controller")
    if controller is None:
        controller = root.find(".//Controller")
    
    if controller is None:
        raise RuntimeError("Controller tag not found in L5X file")

    name = controller.get("Name")
    if not name:
        raise RuntimeError("Controller tag has no 'Name' attribute")

    print(f"Controller name found: {name}")
    return name


def cleanup_temp_file(l5x_path: str):
    """Delete the temporary L5X file"""
    if l5x_path and os.path.exists(l5x_path):
        print(f"\nCleaning up temporary file")
        try:
            os.unlink(l5x_path)
            print(f"Temporary file deleted")
        except PermissionError:
            print(f"Temporary file in use, will be cleaned later")
    else:
        print("\nNo temporary file to clean up")
        
async def close_project():
    """Properly close the project asynchronously"""
    print("Closing project...")
    await project.close()
    print("Project closed")

async def upload_to_new_acd(new_project_path,comm_path):
    """
    Main method
    """

    _ = await LogixProject.upload_to_new_project(
        new_project_path, comm_path, None
    )

    print(f"newProjectPath = {new_project_path}")
    print(f"controllerPath = {comm_path}")
    print("Upload To New Project DONE.")
    
async def get_controller_name_from_acd(acd_path: str) -> str:
    """Main workflow - runs all steps in correct order"""
    project = None
    l5x_path = None

    try:
        # Step 1
        project = await open_project(acd_path)

        # Step 2
        l5x_path = create_temp_l5x_file()

        # Step 3
        await save_as_l5x(project, l5x_path)

        # Step 4
        controller_name = parse_controller_name(l5x_path)

        #print(f"\n>>> SUCCESS: Controller Name = '{controller_name}' <<<")
        return (project, controller_name)

    finally:
        
# Step 5 (always runs)
        cleanup_temp_file(l5x_path)
#        if project:
#           print(f"\nClosing project...")
#           project.close()
#          print("Project closed")